[build]
  # Carpeta que contiene el código ofuscado final
  publish = "dist"
  # Comando para ofuscar y construir
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Elimina la sección [dev] y [[redirects]] si no tienes lógica compleja, 
# Parcel manejará los paths, pero si necesitas el redirect 404:
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200