[build]
  # Publicar la carpeta 'dist' que genera Parcel
  publish = "dist"
  # Ejecutar el comando de build que pusimos en package.json
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Esta parte es vital para que las recargas de página funcionen
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200